### ISSUE TITLE
if maven project please add pom.xml,other add lib jars. thanks!

### ISSUE THREAD

**Issue by ambition119** [philippphb/GRIB2Tools#1]
please add test java file，thanks！

**Comment by philippphb** [comment]
There shoudn't be any other dependencies than the standard java framework. Can you provide more info on the issue you run into?

**Comment by philippphb** [comment]
What do you need for a test file? A basic running example to load a GRIB2 file and print out some basic info?

**Comment by philippphb** [comment]
I added file GRIB2FileTest.java together with some test data in folder res. This is a working example that shows how to use the library.
