### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by reymalahay** [philippphb/GRIB2Tools#4]
Hi all,

Is this library available in a public maven repository?

Please advise.

Thanks in advance,
rey malahay

**Comment by philippphb** [comment]
Hi,
unfortunately, the library is currently not available in any public Maven repository.
I added a jar (in the lib folder), I hope this helps for now.
Cheers

**Comment by reymalahay** [comment]
Hi there,

Thanks for the response. No worries. I'll build the module myself. I was hoping there was an official release available for public consumption.

Thanks all the same,
rey malahay
