### ISSUE TITLE
What does this really mean? "SEVERE: Grid Definition Template Number 3.30 not implemented."

### ISSUE THREAD

**Issue by randycasburn** [philippphb/GRIB2Tools#5]
I answered my own question. There is a difference between GDT 3.0, 3.12, 3.30 etc.

**Comment by philippphb** [comment]
That‘s correct, template version 3.30 isn’t implemented yet. It would be quite easy to do so. The more challenging aspect is how the actual data is decoded from the template, which may require detailed knowledge about the data and the template. If you are interested in adding handling of template 3.30, Please leave a pull request, I would be happy to add this to the library.

**Comment by randycasburn** [comment]
Your use of class names is still a bit confusing. When the # 30 is pinned onto the end of a template class that exends from a class with 3x pinned on the tail, it would seem that GDT 30 (as it is numbered within the file) would be supported. So I still don't understand that use of 30, but I'm certain you have your reasons.

Pull request is unlikely as we already have a solution that works. I was looking too streamline things a bit with an existing solution that I could modify. No time in the project to write this.

Thanks for your reply.
