### ISSUE TITLE
Accessing data causes IndexOutOfBoundException

### ISSUE THREAD

**Issue by Timelessprod** [philippphb/GRIB2Tools#7]
Hi !

I have an `Array[Byte]` representing the content of a GRIB2 dataset. Because I want to be able to get value at specific location, I wrote this variable's content to a file which I'm then loading as an `InputStream` to use it with the `getValueAtLocation(id, lat, long)` and/or `interpolateValueAtLocation(id, lat, long)`. I can perfectly read the metadata of the file, but as soon as I call one of those 2 previous methods, I get an IndexOutOfBoundException.

Here is the Scala code I use to write the GRIB2 bytes array (variable `bytes`) on a file and then load it as an InputStream :
```scala
val file: File = new File("my-data.grib")
FileUtils.writeByteArrayToFile(file, bytes)
val input = new FileInputStream("my-data.grib")
val grib: RandomAccessGribFile = new RandomAccessGribFile("my-grib", "my-data.grib")      
grib.importFromStream(input, 0)
```
According to your README I am doing it right, isn't it ?

Then I can easily get those metadata from the GRIB2 (using some code of your [GRIB2FileTest.java](https://github.com/philippphb/GRIB2Tools/blob/master/src/com/ph/grib2tools/test/GRIB2FileTest.java)) :
```
Body format : GRIB2
Date: 12.10.2021
Time: 9:0.0
Generating centre: 85
Forecast time: 5
Parameter category: 0
Parameter number: 0
Covered area:
   from (latitude, longitude): 51.47, 348.0
   to: (latitude, longitude): 37.5, 16.0
```
When calling `getValueAtLocation(id, lat, long)` and `interpolateValueAtLocation(id, lat, long)` with `id = 0` and `lat = 48` and `long = 2` (which seems to be ok when reading the metadata) I got this :
```
java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:551)
	at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:327)
	at com.ph.grib2tools.grib2file.RandomAccessGribFile.interpolateValueAt(RandomAccessGribFile.java:196)
	at com.ph.grib2tools.grib2file.RandomAccessGribFile.interpolateValueAtLocation(RandomAccessGribFile.java:133)
```
The faulting line seems to be this one in your [RandomAccessGribFile.java](https://github.com/philippphb/GRIB2Tools/blob/231dda8262187a00c3f268d686b6989bcab600cb/src/com/ph/grib2tools/grib2file/RandomAccessGribFile.java#L196) :
```java
float val11 = sec5.calcValue(ByteBuffer.wrap(data).getShort((jidx1*gridDefinition.numberPointsLon+iidx1)*bytesperval));
```

Am I doing something wrong or is there an issue with your code or my GRIB file ? The file comes from a national forecast agency and should be ok. I give you the structure of the GRIB2 file in the screenshot attached (from the Panoply software).

![image](https://user-images.githubusercontent.com/69579602/137101562-65f3c63c-8c19-41b8-9dfa-f1c19d4b0feb.png)

Thanks

**Comment by Timelessprod** [comment]
@philippphb According to this [https://github.com/spidru/JGribX/issues/16#issuecomment-944513342](issue) I made for another GRIB2 library, the issue is due to the Data Representation Section (DRS) of my GRIB2 file. Indeed, the files I collect from my country's forecast organization use a simple packing whereas your library may be using complex packing only. So that may be the origin of the errors I get.

As I cannot ask the national forecast organization of my country (Météo France) to adapt their data to that constraint, can you consider add the support for simple packing DRS in your future versions of the library ? If so, have you any idea of when it'll be released ?

Thank you very much.

Sincerely.

**Comment by philippphb** [comment]
Wrt your comment https://github.com/philippphb/GRIB2Tools/issues/7#issuecomment-945436016, this should not be th issue, as simple packing is supported

**Comment by philippphb** [comment]
Hello @Timelessprod, hope you are doing fine and the lib is working well for you.

I am using the extensions we added together also in my projects, too, and I fixed some issues and added some improvements. Most of them will probably not have effect for you, but there is one bug that adds location inaccuracy when accessing data.

Please sync with the latest commit to fix the issues.

**Comment by Timelessprod** [comment]
Hi,

Thanks for the update. I will transfer it to my manager as I've now quitted the job where I used your library.

Have a nice weekend !
